#!/bin/sh
set -e
if [ -z "$D" ]; then
  # Add boot script to rc.local
  if [ ! -f /data/rc.local ]; then
    echo -e "#!/bin/bash\n" > /data/rc.local
    chmod 755 /data/rc.local
  fi
  if ! grep -q "/data/opt/mod-persist/boot.sh" /data/rc.local; then
    echo "/data/opt/mod-persist/boot.sh" >> /data/rc.local
  fi

  # Link feeds file
  ln -sf /data/etc/mod-persist/persisted_opkg_feeds.conf /etc/opkg/persisted_feeds.conf
fi
