#!/bin/sh
set -e
if [ -z "$D" ]; then
  # Clean rc.local
  sed -i "s|^/data/opt/mod-persist/boot.sh$||g" /data/rc.local
  
  # Remove feed link
  rm /etc/opkg/persisted_feeds.conf

  echo "Package removed. Configuration files, packages, files and patches were not removed nor rollbacked."
fi
